from fvcore.common.config import CfgNode as CN


_C = CN()

_C.VERSION = 0.1
_C.CUDA = False
_C.OCL = False


_C.SYSTEM = CN()

_C.SYSTEM.LOG = CN()
_C.SYSTEM.LOG.SAVE = False
_C.SYSTEM.LOG.SHOW = True
_C.SYSTEM.LOG.PRINT_PERIOD = 10


_C.SERVER = CN()

_C.SERVER.CLOUD = CN()
_C.SERVER.CLOUD.HOST = []
_C.SERVER.CLOUD.PORT = CN()
_C.SERVER.CLOUD.PORT.STEREO_L = 0
_C.SERVER.CLOUD.PORT.STEREO_R = 0
_C.SERVER.CLOUD.PORT.RGBD = 0
_C.SERVER.CLOUD.PORT.DETECTION = 0
_C.SERVER.CLOUD.PORT.MONO_DEPTH = 0
_C.SERVER.CLOUD.SIZE = CN()
_C.SERVER.CLOUD.SIZE.STEREO_L = [1920, 1080]
_C.SERVER.CLOUD.SIZE.STEREO_R = [1920, 1080]
_C.SERVER.CLOUD.SIZE.RGBD = [540, 360]
_C.SERVER.CLOUD.SIZE.DETECTION = [540, 360]
_C.SERVER.CLOUD.SIZE.MONO_DEPTH = [540, 360]
_C.SERVER.CLOUD.SEND = False

_C.SERVER.UNITY = CN()
_C.SERVER.UNITY.HOST = []
_C.SERVER.UNITY.PORT = CN()
_C.SERVER.UNITY.PORT.STEREO_L = 0
_C.SERVER.UNITY.PORT.STEREO_R = 0
_C.SERVER.UNITY.PORT.RGBD = 0
_C.SERVER.UNITY.PORT.DETECTION = 0
_C.SERVER.UNITY.PORT.MONO_DEPTH = 0
_C.SERVER.UNITY.SIZE = CN()
_C.SERVER.UNITY.SIZE.STEREO_L = [1920, 1080]
_C.SERVER.UNITY.SIZE.STEREO_R = [1920, 1080]
_C.SERVER.UNITY.SIZE.RGBD = [540, 360]
_C.SERVER.UNITY.SIZE.DETECTION = [540, 360]
_C.SERVER.UNITY.SIZE.MONO_DEPTH = [540, 360]
_C.SERVER.UNITY.SEND = False


_C.SW_INFO = CN()

_C.SW_INFO.STEREO_L = True
_C.SW_INFO.STEREO_R = True
_C.SW_INFO.RGBD = True
_C.SW_INFO.DETECTION = True
_C.SW_INFO.MONO_DEPTH = True